#!/bin/bash
source .doorconf
sleep .2
now=$(date +"%T-%m-%d-%y")
toBeKilled=$(pgrep -f 'python3 TheDoor.py')
sleep .1
sudo kill -15 $toBeKilled
sleep .1
toBeKilled=$(pgrep -f 'rc522_reader')
sleep .1
sudo kill -15 $toBeKilled
sleep .1
toBeKilled=$(pgrep -f 'python3 TheDoorConfig.py')
sleep .1
sudo kill -15 $toBeKilled
cd $pathtodoor
echo "$now : SetupCards.py is starting up"
python3 SetupCards.py
exit
